---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

inputs:
  - name: source-code
  - name: platform-automation-tasks
  - name: platform-automation-image

params:
  - NAME: simon

run:
  path: source-code/tasks/hello-world/task.sh